[package]
name = "numbase"
version = "0.1.0"
authors = ["Do Duy"]

[dependencies]
stdweb = "0.4.2"
yew = { git = "https://github.com/DenisKolodin/yew", rev = "d0854c" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
